# This file was automatically generated by Spank 0.9.5
# See http://nurd.se/~noname/spank for more information

SRCS= ./pds2png.c
OBJS= /tmp/pds2png.tempfiles/.___pds2png.c.o
CFLAGS= -std=c99 -ggdb -Wall -DSPANK_COMPILER_GCC -DSPANK_ENV_UNIX -D'SPANK_NAME="pds2png"' -D'SPANK_BINNAME="pds2png"' -D'SPANK_VERSION="0.1"' -D'SPANK_HOMEPAGE="none"' -D'SPANK_AUTHOR="author of pds2png"' -D'SPANK_EMAIL="nomail@example.com"' -D'SPANK_PREFIX=""'  `PKG_CONFIG_PATH=$PKG_CONFIG_PATH:.:spank:/usr//lib/pkgconfig pkg-config --cflags libpng`
LDCALL= gcc -o pds2png /tmp/pds2png.tempfiles/.___pds2png.c.o `PKG_CONFIG_PATH=$PKG_CONFIG_PATH:.:spank:/usr//lib/pkgconfig pkg-config --libs libpng` 
COMPILER=gcc
TARGET=pds2png

all: pds2png

/tmp/pds2png.tempfiles/.___pds2png.c.o: ./pds2png.c
	@-mkdir -p /tmp/pds2png.tempfiles
	$(COMPILER) -c ./pds2png.c -o /tmp/pds2png.tempfiles/.___pds2png.c.o $(CFLAGS)

pds2png: $(OBJS)

	 $(LDCALL)

clean:
	@-rm -f /tmp/pds2png.tempfiles/.___pds2png.c.o
	@-rm -f $(TARGET)
